# Generated by Django 3.2.6 on 2021-12-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
