# Generated by Django 3.2.6 on 2021-12-07 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
