# Generated by Django 3.2.6 on 2021-12-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='user_type',
            field=models.CharField(choices=[('health_inspector', 'health_inspector'), ('public', 'public')], default='public', max_length=50),
        ),
    ]
