# Generated by Django 3.2.6 on 2021-12-08 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_organdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organdonation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
