# Generated by Django 3.2.6 on 2022-01-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_vaccineinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='house_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='ward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
