# Generated by Django 3.2.6 on 2022-01-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220108_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='user_type',
        ),
    ]
