# Generated by Django 3.2.6 on 2021-12-09 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_inspector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinedrive',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
