# Generated by Django 3.2.6 on 2021-12-07 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_covidinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidinfo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
