# Generated by Django 3.2.6 on 2021-12-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_covidinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20),
        ),
    ]
