# Generated by Django 3.2.6 on 2022-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_covidinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='labregister',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
