# Generated by Django 3.2.6 on 2021-12-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregister',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
