# Generated by Django 3.2.6 on 2022-01-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregister',
            name='user_type',
            field=models.CharField(choices=[('health_inspector', 'health_inspector'), ('asha_worker', 'asha_worker'), ('councilor', 'councilor')], default='health_inspector', max_length=50),
        ),
    ]
